using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PopupAgent.Rce2;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Windows.Storage;
using Windows.UI.Notifications;
using Windows.UI.Xaml.Controls;

namespace PopupAgent
{
    public sealed partial class MainPage : Page
    {
        private static Guid AgentId = Guid.NewGuid();
        private static string Address = $"https://localhost:7113/api/agent/{AgentId}";
        private const string ImageFileName = "popup-agent";
        private const string Base64Image = "/9j/4AAQSkZJRgABAQIAOAA4AAD/4RZeRXhpZgAASUkqAAgAAAAHABIBAwABAAAAAQAAABoBBQABAAAAYgAAABsBBQABAAAAagAAACgBAwABAAAAAwAAADEBAgANAAAAcgAAADIBAgAUAAAAgAAAAGmHBAABAAAAlAAAAKYAAABsBgAAHQAAAGwGAAAdAAAAR0lNUCAyLjEwLjMyAAAyMDIzOjA4OjA3IDIzOjUyOjU0AAEAAaADAAEAAAABAAAAAAAAAAkA/gAEAAEAAAABAAAAAAEEAAEAAAAAAQAAAQEEAAEAAAAAAQAAAgEDAAMAAAAYAQAAAwEDAAEAAAAGAAAABgEDAAEAAAAGAAAAFQEDAAEAAAADAAAAAQIEAAEAAAAeAQAAAgIEAAEAAAA3FQAAAAAAAAgACAAIAP/Y/+AAEEpGSUYAAQEAAAEAAQAA/9sAQwAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ0NB8nOT04MjwuMzQy/9sAQwEJCQkMCwwYDQ0YMiEcITIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy/8AAEQgBAAEAAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A9/ooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigDM1rXtP0C0FxqE3loTgYVmzyB2B9RWVYeP/AA/qM/lQ3bbv9qKRf5qK5vWFbxP49h05wzW1oA7Jxg52k/yNdPqPgXRL+3WNbSOBl6NEign68Vz89STfLayPY+rYOjTgsRzc0lfS1kntodDDPHcRLJE4ZGGQRUleYHTPFfg52fTnF/YD/lk38A9SeM9P1rr/AA54rstfjKI2y5T78Zxn+Zq41bu0lZnPiMA4R9rSkpw7rp6rodBRRRWp54UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVi+J9cg0HRprmRwJCpEa5HLYJH8q2q8z8Szt4n8bW+gQMClqfMuMr93pjrjP3xWdWTjHTdndl+HjWre/8ADHV+iL/w70W5i+16xfIRNdOWjznIXJyCPyrvajt4Vt4EiQAKoxxUlOnDkjYyxeJliazqPr+XQQgEYIyK838d6MmhCLX9NUQtFIpmwxy3I4wc+lek1wXxOv430ZNHTm4upFCD0OR/jUV0uRtnVlEprFwjHZvX063Ox0m4a70m1nf70kSsfxANXKz9EieHRLKNxhlhQEf8BFaFax2RwVUlUlba4UUVT1DVLPTIfMupgg/P+VDdtyYxlJ8sVdlyqd9qtjpq7ry7hh448yQLn8zXD3HjfVNbmki8OWXmRLx50nAP0yAR2p1t4DutYnM3iW6edMYWFWIHbnIasnVctIK/5HpRy+NL3sXLl8lrL7v8ya++I9vLM1votvLeyg7SUUnB/AHjrVJ5vHWtlUtwNOx82+RMgj0+aOu5sdE07T0Vbe1jXaMA7Rn860AMDApeznL4pfcP67h6X8CkvWWv4bFbT47iKwhS7cPOF+dh0JqzRRW60PLk+ZtjZBmNhnHFeQ6JL408QtcHT9ZjjjhfYRJGg5wD/cPrXr7fdP0rzn4ZuLa71Syf/WiUvj22xisKqvKKuevl0/Z4etUUU2uW10n1d9yOCbx5pMjJOv2/PRljwB+UdTxeO9V098avpM6LnBcI2B/46K9EqCeztrlSs0Ebg/3lBo9lJfDIj6/RqP8Ae0V8tP8AgGBp3j7w9qUxiivVRgM5lIQfmTXSqyuoZWDA9CDXKa94D0vVod0MQguFHyOgxjr2BHrXNW2r+IvBsxi1SJ7mw3AeaG3EDue/rR7SUH7607lfU8PiY3wkrS/llv8AJ9T1GisnQ/EWn+ILXz7GbcO4IIIP4gVrVsmmro8upTnTk4TVmgqve39rp8Bnu544Yx/E7BR+tSXE8dtA80rBUQFiT6CvLboXfxA8QvbRTn+y7Z8PgEBuTwRkf3aipU5dFuzrwWEVduU3ywju/wCup05+JfhoSmP7U5YHHCf/AF66q3uIbqFZYJUkjboyMCD+VYr+DtFfTUsms08tVCggYbA9+tct4EvrrTvEl94buZNy26713NnGdpA/8eqFOcZJT6m8sNhq9KU8NdOGrT6ruj0iiiitzygooooAq6jfwabZyXNw+yNRya4P4c2Mt5qN/wCIbtX8+fMayEj5kwhz69R+lYfxHv8AWf7cbTvtKtayplbeMBiRluTxnoPXtUHhjUPElxp/kaOY/Li4K9SDx/sn1FccqqdRK2x9Ph8tnTwEpxkrztr2X/BPaajlmjgQvK4VR1JrzddD+I0o3jW7aMNztZFyP/IdLH8P9c1J92uawzHOT5BAz/46K19rJ7RZ5v8AZ9COtSvG3ldv8kbmvePLDT4THYulzduP3aryM89eR6VmeH/Deoa1qS654jQCUNuitxghMEYPOf7oPXvXQ6P4O0rSNrxQBpR/GSc59etdD0pqnKTvP7hSxdKhB08KtXvJ7/LsIAFUKBgAYApaKK2PLMjxFr9t4f0yS6nYbwpKJ/eOK4rS/Duo+Lr7+1NfDR2+7dDACPu5OM/e7Yp2oTN4v8cR6bHsa1sWWR2zww+QkAj6mvR4YlghSJBhVAArnt7WWuyPYc/qFGKgv3kldvsntb1K9hpdlpkXl2dtFCvfYoGfyq3RRXQlbY8mUnJ3k7sKKKKCQooooARvun6V5t4E/wCRt1X6f0jr0lvun6V5t4E/5G3Vfp/SOsanxxPVwH+7V/RfmelUUUVseUFQXdnb30DQXMSyRsMFWGanooGm07o4K68CXNhqcd34fvTaqXzIhHBHoMAY6mu6iDiJRIQXx8xHTNPoqIwUdjor4urXSVR3t16/NnJeO7TVtR0+Gw06DzI5nAmYHBUZx6+hNanhrQLXQNLjggjCyMoMjEDJPuQPc1s0UKC5uYcsXN0Fh1pFO/r6hXmniGGLSfiFp9/GoTz5FEpA5blMfoK9Lrg/iCP9N0g/9N1/9CqK692/Y6MqlbEcvSSa/A7pGDxq46MAadUVt/x6w/7i/wAqlrY857hTZG2Rs5/hBNOqK5/49Zv9xv5UAtWedaDbDXPHmoX1xHvjgcpHuOdvL/40vifSrjwrqX9u6MH8t/8Aj4gUnbjHXGcDhR2q98Pv+PzV/wDru3/oVdvcW8V1A8M8ayRuCGVhkEVzQpqUL9T3MTjJYfF8u8UkmujVihoes2+t6clzAwPHzD0PI/pWnXl0v2jwB4kDxnGlXbcoeinjPQj+8e1elWd1Fe2kVzCcxyKGB9iM1pTnzaPdHDjcKqTVSnrCWz/T1RPRRRWpwBWdruof2Zo1zdAgOiErnua0a5H4jf8AIqy/U/8AoJqKjtFs6cHTVWvCD2bRnfDHT5EsbvUpxlruYyIT1A6Y/Su/rJ8NRRxaBarGiqMHgDH8RrWpUo8sEi8fWdbEzm+/5aBRRRWhxhRRRQAUUUUAI33T9K828Cf8jbqv0/pHXpLfdP0rxjSbHWb3xPqI0i++yuPvHBORhPQj2/Kues7Siz2crgp0a8XK2i1fqe0UV5rcWvj/AEnbPBdLqTf88myB+rimf8JB8S/+hfsvzH/x2n7e26f3GaypyV4VYNf4rfmem0VyHhXVPFt7fyx6/plvawBMo0R5LZHH327Zrr61jLmVzhxFB0J8jafo7r7woooqjAKKKKACvM9UuH8SfEaLSwh8mxZZJPm6j5Dn/wAervdY1SHSNNlu5vuoM49a4v4b2ElxLea7dAtPcMQjnqUwB9f4awq+9JQR62Xr2NKpiZdFZer/AOAegogjjVB0UACnUUVueSFRXP8Ax6zf7jfyqWorn/j1m/3G/lQOO6OJ+H3/AB+av/18N/6FXd1wnw+/4/NX/wCvhv8A0Ku7rKh8CO/NP96l8vyKWq6bBq1hJaXChkcdD69q4Gwvb3wJqJsr5GbSZZD5UgHCcnHOB7V6XWdrWi2muWLWt5HvQ+5B/MH2oqQb96O5OExUaadKsr03v5ea8y7BPFcwrNDIskbDKspyCKkry7StW1DwTqI0/VgW0922xyEk7ePoc9DXp0MyTxLLGwZGGQRTp1FNeZOMwcsPJNO8Xs+4+uR+I3/Iqy/U/wDoJrrqzPEGmDVtFuLXALsh2Z7GnUV4tIjB1FTxEJy2TQnh0g6Da4OflP8A6Ea1K4X4bapJPp9zp0+RLZymMbjyw65x+Nd1RTlzQTKx1GVHEThLv+YUUUVZyBRRRQAUUUUAI33T9K828Cf8jbqv0/pHXpLfdP0rzbwJ/wAjbqv0/pHWNT44nq4D/dq/ovzPSqKKK2PKCiiigAooooAKRmCKWY4A5JNL0rg/Gev3NzPFomisWupTiVlBIQZHfHse9ROagrs6MLhpYiooR07vol3M3Xbu88Z+ITo9iUFhAf3soOd33hgcH1FekWltHZ2yQRDCIMAVjeFfDkWgaaiEbrlwGlfrlsDPf2rfqacGveluzox2IhO1Gj8EdvN9WFFFFannhVPVJ/s2mXEuM4jPH4Vcrj/iRqL2XheSOB8XMzKsa8Zb5lB/Q1E5csWzowlF1q8Ka6tFX4axvNYXWpkYjupWZR6c5/rXdVg+DLJbDwnp0YXazQRu49GKDNb1KkrQSNMwqKpiZyW1/wAgooorQ4zH8Q+H7PxBp7W91GpYco+BlTgj+prlfh9qVyl/f6NdTPKYH/d7iThevf616FXN6d4WWw8VXWspKcToF2Z4HAHp7etZTg+dSiejh8TH6tUoVXpa8fW50lFFFannHmV4kvhHx8L8BUsr4qjcfKv3AcAd+telQypPEkqHKsAQaw/F/h5fEWiS2wCicAmNj646dDwTiuV8LeLJdFkbRfELeXLEdscpIAI59cccDHFc6fs52ezPZqU3jsPGpDWpDRrq10f+Z6TRUUFzBdRiSCVJEYZDKcg1LXQeO007MKKKKBBRRRQAjfdP0rzXwCwfxVqjKcqQcH8I69Kb7p+ledfCxR5eptjn7QRn/gCVjU+OKPVwT5cJXl5Jfez0aiiitjygooooAKKKwvFeszaJpDXEELSSZwPToT/SlKSirs0pUpVZqnHdmJ418YNYI2l6Z+81Cb5BjPy5A78YPI5qfwV4XfTYTqF+xlv5/mZm5Izn6+vrXEeFdc0ux1K41TXFke9lfcr4XjGMdx0wK9E0/wAdaDqDlVvEhIxjznVc59OTXLTlGcueT9Ee9jMPWw1H6vQg7fal38vQ6SimRzRzIGjdWUjIIOc0+us+dasFFFFABXm3itLnxF4v0/ToY5PJtHEjMUIBGVJGcf7Nek1ELaAT+eIkEvTftGfzqKkOdWOvB4n6tN1Eruzt5Ni28Qgt44gMBFC4+gqSiirOVu7uFFFFAgooooAKKKKACsbWvDGma7EVvIMk/wASsVP6EelbNFJpNWZdOrOlJTg7PyPN08E+IdJmf+yNUPkk8LMcgD2yTR/b3jKxt1Eth5oU4JUcn/xyvSKRlVhhgCPQisvY2+FtHo/2nKb/AH8Iy+Vn+BwNr8So7YlNasZ7Pb1dkY5/8dHtXQ6d4x0TU4TLb3qBf9v5D+RrRudH068ObixtpT/txK38xWBdfDjw3d3DzPZ7WY5whCqPoAKVqq2aY3PLqqvKMoPy1X3P/M6mKVJo1kjYMjdCD1p9Q2lrHZWsdtFny4xhcnJqat0eXK13bYRvumvJPDniHRvCGtapbXWoEw+Z8hWMtuyqc8Z9CK9crKPhrRCcnSbIn/r3T/CsqkJSaceh34LE0qUZ06ybjK21unrcwP8AhafhX/n9k/78v/hR/wALT8K/8/sn/fl/8K3v+EZ0P/oE2P8A4Dp/hR/wjGh/9Amx/wDAdP8ACptW7o058s/kn/4Ev8jOh8f+H54xIl58p9VI/nUi+N9CZgouxknHSiTwL4flkZzYRAnsqKB/Ko3+H/h10KmxUAjHAA/pT/feQ/8AhNf8/wCBrxa3ps+PLvIST/tj/GrUkdveR7W2Spnsc1xM3ww05HLafcS2uf7rnP6Yro/D2hyaJbPFJezXW5s5kYnHA9T7U4ubdpIxr08LGPNQqNvs1YsvomnP961Q1jal4A0PUSXaApIDlWWRxg/gwrqaKtwi90YU8XXpPmhNp+p5vH4K8SaVK40vV2eMnjzzuwPxJxSpd+N9LaSJ4kusc71GO3+6a9HorP2KXwto7Hmk5/xoRl8tfvRwGmeOb9NRjtNW02eLzGCq4RiM9Oy/Su+UhlBHQ1DJZWsrq8lvEzLypKAkVP0q4Rkt3c5cVVo1WnThy9+wUUUVZyhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB/9kA/+EMzWh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNC40LjAtRXhpdjIiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpHSU1QPSJodHRwOi8vd3d3LmdpbXAub3JnL3htcC8iIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1wTU06RG9jdW1lbnRJRD0iZ2ltcDpkb2NpZDpnaW1wOjExODkzYTdmLTMyNzgtNGVlZi1iNGQyLTY4YzYyMjVhNGRiZCIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDo4MDM3ZmEyMC05ODljLTQzZjUtYTJkOS0wMWJhMjY5M2MxNDciIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpjZjc0NDU2ZC02YTIwLTQ1ODQtODhlZi05NmFmMmNmZjBmYzEiIGRjOkZvcm1hdD0iaW1hZ2UvanBlZyIgR0lNUDpBUEk9IjIuMCIgR0lNUDpQbGF0Zm9ybT0iV2luZG93cyIgR0lNUDpUaW1lU3RhbXA9IjE2OTE0NDUxNzY3NjYxMTgiIEdJTVA6VmVyc2lvbj0iMi4xMC4zMiIgeG1wOkNyZWF0b3JUb29sPSJHSU1QIDIuMTAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjM6MDg6MDdUMjM6NTI6NTQrMDI6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDIzOjA4OjA3VDIzOjUyOjU0KzAyOjAwIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0OmNoYW5nZWQ9Ii8iIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MTYwYmM3OTItOTM4OC00YjY5LWJiMmItMTkzNmM2YTUzZTIyIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJHaW1wIDIuMTAgKFdpbmRvd3MpIiBzdEV2dDp3aGVuPSIyMDIzLTA4LTA3VDIzOjUyOjU2Ii8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8P3hwYWNrZXQgZW5kPSJ3Ij8+/+ICsElDQ19QUk9GSUxFAAEBAAACoGxjbXMEMAAAbW50clJHQiBYWVogB+cACAAHABUAMgA2YWNzcE1TRlQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANZGVzYwAAASAAAABAY3BydAAAAWAAAAA2d3RwdAAAAZgAAAAUY2hhZAAAAawAAAAsclhZWgAAAdgAAAAUYlhZWgAAAewAAAAUZ1hZWgAAAgAAAAAUclRSQwAAAhQAAAAgZ1RSQwAAAhQAAAAgYlRSQwAAAhQAAAAgY2hybQAAAjQAAAAkZG1uZAAAAlgAAAAkZG1kZAAAAnwAAAAkbWx1YwAAAAAAAAABAAAADGVuVVMAAAAkAAAAHABHAEkATQBQACAAYgB1AGkAbAB0AC0AaQBuACAAcwBSAEcAQm1sdWMAAAAAAAAAAQAAAAxlblVTAAAAGgAAABwAUAB1AGIAbABpAGMAIABEAG8AbQBhAGkAbgAAWFlaIAAAAAAAAPbWAAEAAAAA0y1zZjMyAAAAAAABDEIAAAXe///zJQAAB5MAAP2Q///7of///aIAAAPcAADAblhZWiAAAAAAAABvoAAAOPUAAAOQWFlaIAAAAAAAACSfAAAPhAAAtsRYWVogAAAAAAAAYpcAALeHAAAY2XBhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbY2hybQAAAAAAAwAAAACj1wAAVHwAAEzNAACZmgAAJmcAAA9cbWx1YwAAAAAAAAABAAAADGVuVVMAAAAIAAAAHABHAEkATQBQbWx1YwAAAAAAAAABAAAADGVuVVMAAAAIAAAAHABzAFIARwBC/9sAQwADAgIDAgIDAwMDBAMDBAUIBQUEBAUKBwcGCAwKDAwLCgsLDQ4SEA0OEQ4LCxAWEBETFBUVFQwPFxgWFBgSFBUU/9sAQwEDBAQFBAUJBQUJFA0LDRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU/8IAEQgAlgCWAwERAAIRAQMRAf/EABwAAQEAAwEBAQEAAAAAAAAAAAAGBAUHAwIBCP/EABoBAQACAwEAAAAAAAAAAAAAAAAEBgIDBQH/2gAMAwEAAhADEAAAAf6pAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIKHZvHzZQbuXR7+SAPnz36988/MvT3EAAAeOOcLFsvQJlX57CtPQptW+PMomLYvDHZTb+Put3P5DzL3R7+Th4yLyZWfpjzyFa6mRxKPfyhy/n3LPzjfht9kGrk8TmsG3dCmVbIy1AQUOzXsys/Pns5p6308oN3KholkvJlaHLOfdNvsgXkytCXj9nOzjbrbzwBzaDbeizap6e4gCAh2e/mVgRMSw7DON+FPI48TEsNtLrwAHLoFz2ucKsk8PYZxRGxe/vd3N2uyEIeJYriXXZCN3czLRkZasLCRUSOMAIKHZr2ZWQJ/R1NdhLsZXAGJjvlI/btpVdGk1dDd7efzmDbN9u5lJv5Hp7iIKHZr2ZWQOPcy+VMjjU8jjbHOLrtcvNzjenuIAGo1TpnR2KHdyt5u50NDsnh5s+vfMj3VbS67j47ZrR16bfx/fLWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/xAAkEAACAgICAgICAwAAAAAAAAAEBQIDAQYAEBUgFjUUYBETMP/aAAgBAQABBQL9h2G6ws2apooypd1NPXEsZ6/sh/jdbEerWaJG28aYj8t5Oca427PgiUEjJhlYnFUQ4t18BsfLWJj88uwRWCl0m0kkViUUXPHVaJrlsF1uTymoerbUoNPya9hxOlkHZzFU9rOoHqFr71/7jko4nEJDQuOcp/M4hHFcU9f4mxdWqqtkdoDZ039bKbIFMmB8Yq9ExdAzmFkbI+muzyxZdIvtHafydSZx+fjm2/W+qtWIwdS0ZLKQAFCwXrYmVlNatfWqA61+WLGPHaXJmUbbyozoDyavW2GWKj01/wC47dOaUoyJTOmXRZERBdOplWi6CVwBM4aMUiaA7KuYchZGyPWs/wAfm9wgyrcUbeFKdDEUqPGAFbIWuEaoepSgI3lunjY4rDKDhwnVcXl/Es8+NmcGXuRruXD1EYJ1VYTyirFFP7l//8QAPhEAAQMBBAQJCQcFAAAAAAAAAQIDBAUAERIxECFRYRMUICIyQXGhsRU0QlJicoGR4QYjVGDB0fAwM0OS8f/aAAgBAwEBPwH8w0ptDDDtQdTfh1AHK82TNgTuZMb4M+sgeItOpzkO5d+JByUOTcRowK2f0W0KdWEIGs2rDojpRTGuijPerr0Q7/JErHlzbu2/X3aEpKjcmyKOWgFzlhsbPS+VlVGDF5sFi/2l6z8srTJ784gvnLLdol1SZBjxRHXckoHzsKwl3mymEqG4YT87cQh1JOKnnAv1FHwNnmHY6+DeThO+zTS33A22LybON0mnqEd5JdV6RBuu7NtqlCEF/Ak3pIvB3HT9n6a6twTlJ5qct5H8zsuhVSStTym9ZO0fvbyO1F5098DcNZ+lp9QEhIjx04Gk9W3edGNNEYTgH36xff6o3b7OOuPKxuKvPIqnmcP3T46ASk3i0ipuy2Ay+ASPS9LsvtAn+T8a0J5xFwOyyiVHErO09XD06M6rMXp+WlE5ykwo/A5qJUd4yutU46XECdGN7Z6s8J2aaRHTJmoSvojWewWqEnjkpx/af+cmoMOvQonBoJ5vUN9lJUk3KHJqqREjR4fXdiParq01LzWJ7p8bU6fxNRS4MTaukLVCBxa51o4mlZH9Dv0UPzlXuq8OVMmSYsKIGHCm9PUd9h9pKoBdwvcn9rSZLsx0vPG9R00qIhxRlSNTTes79gtNlLmvqfX16aoCiPFSrPD+uinVAR748gYmlZjZvG+1Sg8RdASb0K1pO61PlcTlIe2Hu67VeKIsxaUdE6x2Hk1TzOH7p8eRT6e7UHcCNQGZ6gLVKchwCJG1NI7950sNF91LScybrV9xKp6kI6KLkj4aZE1cllplQ6AI0R3mKlFTCkKwrR0VHLsP8+smkTYvTReNo1iykqQblDTWL+BibODHIUqCuGmHGkYB6V4Os2doMoJxx7nE+yb+6zkV9k3OII+GiLJXEdDzeYspRWSpWfKZnSo/9pwj42RXnzqkoS4PaFpshiQoFhng/iT46Ga0WmUMmO2rDtF58beXR+Ea/wBfrbyvG/Bo77PSqY8g3RyhW46u/Q2641rbUR2WZrU5n/JeN+uziy6srPX+c//EAC8RAAIBAgQFAgQHAQAAAAAAAAECAwAREBITMQQgITIzIkEUUWBxIzBCUmFigZH/2gAIAQIBAT8B+oZiWYRA71pyR+M3+9RyiTp789/ySbC5qAZiZT74SedLYbUZ79IxetKR/I3/ACo4lj7cEgjkZ8w960LdjVqSReXqPnSsGF1okKLmgZ5fUpsKhk1FvjxMoA0xvQ4mFBlvWuz+Najiy+pjc4W+Ibr2igAvQckPkfFYQjZlqWPVsDtW1RjLK64mMTyNm9qhax033xnbJGbVEmRAvLEyrI9zV78sPrZpMYu96ljzi43qKTP0O+HE9n+80aK8j5hXwkPypEEYyrjM5HoXc1GgjXKMYe5/vhLFm9S71FJqD+alTOhWoHzoL8sPkfkllEQuaijI9b7nFjlF64YWjuffFYwjFvngwaJ9ReoO9JPG+xq98YO5/vyfiB87LehxKbN0oOrbHB0DjKaAtzNGjbijwy/oNqjVl7mvg3D3YtmIvXw39zWi37zSpMp7r4FQd6PDxn2oCwt9Z//EAD8QAAIBAQQGBgUJCQEAAAAAAAECAwQABRESEBMhMUFRFCAiMjNSQmOBkbEjNVNgYWJzoeEkMENxcnSSlLLR/9oACAEBAAY/AvrDRXXDK0JmOskeNsGCC2e76pq2PjT1bbT/ACazxlTBVR+JA+8dXYcdHeHv/cvJIcqIMxJ4C018Tg62o7MWPox8NF0avxcsmtw8uGzH26CzEKo4mzRXZTyV8m7WKMI/8rZrzvDKv0FH2QPbvs60yFc5xdicSx56L4NVBnmWqbA4kEC2aivGpgk9Y2sHutlvVOk03CrgTd/ULCWCVZoz6SHEWeaVssaDEk2eqp5o7vgPgxvHmLjmTwtrHTVTRuYpU5MN+lrtWTLPNgrnyKeNooFqexGoUZY2Oz3Wy3Zd80vKaYZE/Wz1VXN0qvk70uGGUchol1j4XVTvlWNf4zcybCOGNYkHoqMB1L8/HHw0EMMQeBs89M8kSOMDTg/J488LU8by5YEfPJHh4n2WCqAqjYALXtAoAR8s2zmdN5dIxyQIsEZU7VO/G0l2ViqlXHtVwuGuXnpqGjx1rDVphzOy1LTcY0AOHPj1b6100cWMwwzsBwsGVgyncQered4egX1EeHELx031+OP+bI8TamshOaKXlZoJ11FdF4sR+I+zRF/cR/HrXyammjnKzDDWLjhssT0Q7fWv/wC2Snp1yQruGOOlKKlBatquymB7o4taKmj7qDfzPHTfLrtU1GGPs0LV0jam8Iu449L7p+yzF0MVRE2rmjPBrVFPxZeyeR4Wgd/GQauUHzDq35+OPh1NZJ25G2RxLvc2krqw566fafVjyjTLM/djUsbRSSeLUFp2PPMdNZOjE9JYMV4DRLeFJG1TSz+PTp3gfMLDJUKkn0cnZYWxRgw5g6b78/TG92HUlr6y62q3HZhCOMIxbV1Qku+by1K5fzsGiqIpAd2VtDU8ubVtvynCyogyqowAHW+WpYpDvxK7bY0lRU0Deok2WcVNc1aTuLIFw92ieoW8q+BpmzMsMoUfC3zzen+x+lvnyr/Ky43lHUw47dbFgcPZowliSQffXGx/ZhGx9KPsmyRgswQYYscT9c//xAAoEAEAAQMDBAEEAwEAAAAAAAABEQAhMRBBUWFxgZEgMGCx8KHB4fH/2gAIAQEAAT8h+4Ub26Kqjaf6oOZufDfqd7XrEBGR9OTr8ZGCGYfp2Gq6tABK1KsKFsOEdYn/ALepH+w5xouEwUgKISZEBe7PipMG5PO3UhAJnzCd9DlBjYwTD3pAPsXHuqtnZu1vRx4/msC6qgLht6ICkx1Z+UX4HjdZ8FA2zWNfYNjOWzbacNN2gk8BBhcVdzkw71vSB5YSDg9j80sFIV7JxZ4BxWIhQvkJhENCEiV/kkasmgUh7nZiU2ob4gUAcVgkP2ST7b62R4gGWPWaFG0IOyYtPMa96tnjR1o7DJODmvc/EfVWJ3zoacTLCVM/BI238OW3n4ZYhQZd7j0asBsP1ytLfk8NWzDtJpEyKbAeqIXmzuEst2+XWZ0xRcxwBV8e6W5deWdXEjAcKRTw6R6KsI73elnEwRGXjpQ4t/Qbr3TEu0BLTP58/RTukXmNqBW50bjZ4TVBo8FE1dvCW6QfUavtm7KEW76XShGkB+p/kEC+Je0zI13tOjWfBkc2I/vVxbNFcyBTzcHK81bsl2h6mEVmFmFnRPRDdphmO1CREwAfLdoWGT3pVj3Ki7m56p2yE6njlpc4IE4AsbADxp5GQemlr/PMUaBwFgCPugHPpnQebUL8Je8crl+8/wD/2gAMAwEAAgADAAAAEJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJNCJJJJzLMM40o5ZONgVJHHN3JOIrJJSJBJMvMJJIBJjIZFJJI5I1JJJZtZHIebFZJI75u1HnJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ//xAAoEQEAAQQCAgEDBQEBAAAAAAABEQAhMVFBYRCBcSCRoTBgsfDxweH/2gAIAQMBAT8Q/cICSQyVuEhgzqTpoNGuIAPHTuJWO5IEHTid6Y4fpcg8dj7foyjEADKrAUnJZY3lynqY/wAApxOe/wDad/wnvwGKV4KdO7yZR8bjqebJQN06G9LNdkMDQfWMAABogxqZ8OIRJAiFHJOIkGr8/wD+AOe6bMzIL4zZ9/gpkgcgh/NTjGAF7vxRKzlQ9AizmX3dA1HrexL35kQToknGDkhvZEmyr1BLJqrLZG9Uw4Hl/Xa3tb3WW2Caq28utFr5rNik1NMLmwC93K4jFM1Nyqv3fq0MPCYSmkNIjD5LnNye6ZTF8OeWIZktxH3Fekq6uVeWlbLltQT7EB15tNjNJMBdRn0kNPesVKudTeNL1s8xCyXsZGemIeqXh2TowPRB9KySKZGPQpWwTIkJWPoMOPfNDiAue+fP9VvVpwxtOE7OPdSeGH/QGHcW5irv6931GiEmQntFGhYd35ZNW7wlgMAFgDBry6hAkJlwnKudFZX3jQWD0AeROgNjmFI+y54O5ZEvYJt+TBqrAM7ibT3sps2BJtWH2mJtNAlet4zEfGL6n9HTchP8hX/nvAoTmAbfOKV4tbzhkQ9sf7WBcFoIJ6Z8kKAh5RZv8YI8BS1ohfV0vza9HVX5QnEJvTfqpQB0keYD/wCCZZ9xE+vJ3RGWvILRlMBrG5usktol8OQ7CY5aetDMoj8eIeb0SDkib86clPVKZV5X6raNEQKI+MV6Q5U+Ew6UY1QTgTISHenq3gYyYF4JVu8lW0EuK2U0rLQSogxflxOUfEeFVC7J/FLAIrRYjV/9ozgUsAATewWDQfvP/8QAKREBAAECBAUEAgMAAAAAAAAAAREAMRAhQWEgUXGB0ZGhscFg8DDh8f/aAAgBAgEBPxD8hiVXMXgpXMLkvupyEC48MjhDn/CTJAUt52dMOo5z0jL3wUEtT1T56etGYi2yHreg0F774M0yL0pedR3zqbA2B8lSYkpw2RRCTSIlev75rMhCMPUxetCvsP7aggyByfFWjO7kUzZzr9GEmlmW5tGQwcHucEEhpuiDpp1rNDIynOgBBUUWYfXHQEANtZpWKB2k54qi5yO9bHn+8MIxnq0ASPC3Tpg6GuPvfqo5IFms0cG59m2Fjo+eKGBz1pRn5PmgoQHf5xNNm23oTpYqWLeGDMeDZ57NTqkDJN63I+aR1xk9Th9zwalGxzaYc72tjEVdgphuSXviQnA6HQC/UrQB5OTQBI497LgBM9pCZUxzHuRRUg98EdloABbisu0LNHs0OnpIjCGNoQ+ql/eeMOASRueMMjI1ys7ZURDT8z//xAAlEAEBAQACAgICAgMBAQAAAAABESEAMUFREGEggXGRYKHwMMH/2gAIAQEAAT8Q/wAhe5U/WQBqMzb9IoP0qsA17aQwPoRERfr+kqzekf6pfwaCSgBn8/GyaiiRiYnfBpTT/wADuzsQkLgALXkX+EbRC4UK/fk/AFWj3pbLo1/c+vgAqRwPavXPXyEB6wAKL6NFOAmtQ4zl7EB3pUqcJSQu91TqtQLfhf8AFhrwA1UKP+uDCUpYuiGn1Trg9gNbsVyeBgA8rtKQoSiMSnkcTs4R/CABe1C+O+Vyc8Yuhrwpj6HB/wD6CBB9NH6s8fPacactkKBHZ0x4JKHgkVgzot4M7l0u6DsfRvWTeK0HN4sP0wr2i5ZwEVANV8cWYgznThEyAG13N6VoevbAC/f4f9j0+HS+OJdiOJxYzQ1pGEWIGIBYa8Cc1IAbSSO+b6sQaB2hyADAACcAaA8gozO6J8r895qE0OR0Qi3tGnIMZS4AICnpXT6YAdE+G+B5ndT0FUuULyZJxEQRDpWp4v4utsCEFSi8DY4g90iMTgBRE9nysOKESZC5ExhNEyKeL8/8704WV0p/sqWnsHxG3ucJfVfQRLKD2Lxi1gUX+PBpTr8UXQpAlSGXgAzGElfAIH0YcdOLU69lWjr8okYMXnfdCPl665V6D2GKftF+/kue5UkJ9gieH4Kmc2MGKGj0OFfby3CMAB0VXcfpPHHyl5/pLYAs2U41nPPhugCwxhjx+P8A2PT8BuEcqYBsqV+wKoL5sft21KgQd2f38P8AIkQUaC5WQ+043x15lAni3nu/JzijK9ZLpVvn4EPpQ2QdVfI2qaPF88i0uiPrqlPS8BNeAm/ZnykFUSfH/Tuf380KBjBZyqTyEPIhNqtWTAkPKhl3HVUFSzDn2WFmzAd34ZdDIIFE7SaOJ3wcEHQRAD+PyZV5YjRqAXt7eJqU16WXuiUGp2Xi7nzZCOnbGu58YZW4Io0xiqwVeMGV8UpwAYBCv/8AN4OA8q+IxBlir8bmtEv4AfR/XFktXieCoR2SfXDSF6EALlSauv8Amf8A/9k=";

        public MainPage()
        {
            InitializeComponent();
            _ = Task.Run(SetUpPopupAgent);
        }

        private async Task SetUpPopupAgent()
        {
            await GenerateImage();
            await DisplayToast("Startup test");
            _ = Task.Run(FeedHandler);
        }

        private async Task GenerateImage()
        {
            using (var memoryStream = new MemoryStream(Convert.FromBase64String(Base64Image)))
            {
                using (var fileStream = new FileStream(
                    $"{ApplicationData.Current.TemporaryFolder.Path}/{ImageFileName}", FileMode.Create, FileAccess.Write))
                {
                    memoryStream.CopyTo(fileStream);
                }
            }
        }

        private async Task DisplayToast(string text)
        {
            var templateContent = ToastNotificationManager.GetTemplateContent(ToastTemplateType.ToastImageAndText01);
            var templateContentTexts = templateContent.GetElementsByTagName("text");
            for (var i = 0; i < templateContentTexts.Length; i++)
            {
                templateContentTexts[i].AppendChild(templateContent.CreateTextNode(text));
            }

            var imagePath = $"ms-appdata:///temp/{ImageFileName}";
            var templateContentImages = templateContent.GetElementsByTagName("image");
            templateContentImages[0].Attributes.GetNamedItem("src").NodeValue = imagePath;

            ToastNotificationManager.CreateToastNotifier().Show(new ToastNotification(templateContent));
        }

        private async Task FeedHandler()
        {
            using (var httpClient = new HttpClient())
            {
                while (true)
                {
                    try
                    {
                        var feed = await httpClient.GetAsync(Address);
                        var content = await feed.Content.ReadAsStringAsync();
                        var rce2Messages = JsonConvert.DeserializeObject<List<Rce2Message>>(content);
                        foreach (var rce2Message in rce2Messages)
                        {
                            switch (rce2Message.Contact)
                            {
                                case Rce2Contacts.Ins.PopupText:
                                    await TryRun(() => DisplayToast(rce2Message.Payload["data"].ToObject<string>()));
                                    break;

                                default:
                                    if (rce2Message.Type == Rce2Types.WhoIs)
                                    {
                                        await TryRun(HandleWhoIsMessage);
                                    }
                                    break;
                            }
                        }
                    }
                    catch (Exception e)
                    {
                        await Task.Delay(1000);
                        // ignore
                    }
                }
            }
        }

        private static async Task HandleWhoIsMessage()
        {
            using (var httpClient = new HttpClient())
            {
                await httpClient.PostAsync(Address, new StringContent(JsonConvert.SerializeObject(new Rce2Message
                {
                    Type = Rce2Types.WhoIs,
                    Payload = JObject.FromObject(new Rce2Agent
                    {
                        Id = AgentId,
                        Name = "Popup",
                        Ins = new Dictionary<string, string>
                        {
                            { Rce2Contacts.Ins.PopupText, Rce2Types.String },
                        },
                        Outs = new Dictionary<string, string>
                        {
                        }
                    }),
                }), Encoding.UTF8, "application/json"));
            }
        }

        private static async Task TryRun(Func<Task> taskFunc)
        {
            try
            {
                await taskFunc();
            }
            catch
            {
                // Ignore
            }
        }
    }
}
